### ISSUE TITLE
Debian 10 Not Supportet 

### ISSUE THREAD

**Issue by Blue-Gamer48** [guldkage/Pterodactyl-Installer#11]
in the Readme.md it says that Debian 12 is supported but the script does not recognize that it is Debian 12 nor does it allow Debian 10 please fix it

**Comment by Blue-Gamer48** [comment]
the bug is also in the Wings Installer

**Comment by guldkage** [comment]
Hello

I apologize for the late response. I did not get a notification about this issue.

The script does currently not support Debian 10, it is a mistake that the README says it is supported.
Please update to Debian 11 or Debian 12.

Debian 12 works with the installer works with the installer as expected.
If it does not work for you, please share screenshots so that I can help you further.

Have a good day!

**Comment by guldkage** [comment]
forgot to mention earlier, but you should consider upgrading to Debian 11 or Debian 12 instead of Debian 10, due to it being EOL

**Comment by Blue-Gamer48** [comment]
I have Debian 12 the Script Say that is Debian 10

**Comment by guldkage** [comment]
Hello
The script gets your operating system directly from /etc/os-release
Please make sure you are on Debian 12.

Also, I would like a screenshot.

**Comment by Blue-Gamer48** [comment]
i have ssl of true and the setup have not create a certificate for the node

**Comment by guldkage** [comment]
Hello
If you selected SSL, the script will try to issue you a certificate using Lets Encrypt. This process can fail.
Here is the most common reasons why it might fail:
- You did not point your domain to your server
- Ratelimiting on your domain at Lets Encrypt
- Failing to bind to port 80 (this will only happen, if you ran the pterodactyl installer without a fresh system.)

Please try to manually issue a certificate, and you can see why it failed to do so in the installation stage.
`systemctl stop nginx && certbot certonly -d <domain> && systemctl start nginx`

With this information I can help you further.
