### ISSUE TITLE
What i can see my phpmyadmin password ?

### ISSUE THREAD

**Issue by SkyAndCraft** [guldkage/Pterodactyl-Installer#13]
Hi, in have use the tool for install my pterodactyl with phpmyadmin, so i have not set a password in the installation.

Is possible to see it or there are a password by default ?

**Comment by guldkage** [comment]
Hello there

Sorry about the late response. I am currently having a lot of exams.

This was due to an error in the code. It is fixed now.

If you installed the panel with SSL on your current installation, the password may actually be your username, and the username will be "admin"
When my exams are over, I will do some testing on this too.

Have a good day
