### ISSUE TITLE
Stuck on "Downloading..."

### ISSUE THREAD

**Issue by MrFr4nk0** [guldkage/Pterodactyl-Installer#8]
During the installation process the script stucks at "Downloading...".
[📄 Console Log](https://pastebin.com/DdnjvEkC)

**Comment by guldkage** [comment]
Hello there

What OS are you using? I will test the script.

**Comment by MrFr4nk0** [comment]
Hi!
I'm using **Ubuntu 22.04** on an Oracle Cloud **ARM64** instance.

**Comment by guldkage** [comment]
Hello

Unfortunately, I don't have an ARM64 machine to test this with.
The problem may be that you are using ARM64, or problems downloading Composer.

You can try stopping the script with CTRL+C and manually installing Composer and see if that makes a difference:
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

After this, you can try to run the script again, since in that case you already have Composer installed.

**Comment by MrFr4nk0** [comment]
Hi
I think the problem is with Composer because when I try to install it I run into the same "Downloading..." problem. I tried multiple ways to install it but none of them worked out.

**Comment by MrFr4nk0** [comment]
Turns out the installation of Composer was just slow as hell.
I needed to wait around 7 minutes and it installed.
